import { fetchedAndSavedAudit } from "../interfaces/cruxApi";

export const countryNamesURLAndCountryCode = [
  {
    url: "https://www.yara.be/",
    countryCode: "BE",
    name: ["België", "Belgium", "Belgique", "Belgien", "Belgia", "Belgium"],
    nameToDisplay: "yara.be 🇧🇪🇳🇱",
  },
  {
    url: "https://www.yara.be/fr-be/",
    countryCode: "BE",
    name: ["Belgique", "Belgium", "Belgique", "Belgien", "Belgia", "Belgium"],
    nameToDisplay: "yara.be 🇧🇪🇫🇷",
  },
  {
    url: "https://www.yaraagri.cz/",
    countryCode: "CZ",
    name: [
      "Česká republika",
      "Česká republika",
      "République tchèque",
      "Tschechische Republik",
      "República Checa",
      "República Checa",
      "Czech Republic",
    ],
    nameToDisplay: "yaraagri.cz 🇨🇿",
  },
  {
    url: "https://www.yara.dk/",
    countryCode: "DK",
    name: [
      "Danmark",
      "Danmark",
      "Danemark",
      "Dänemark",
      "Dinamarca",
      "Dinamarca",
      "Denmark",
    ],
    nameToDisplay: "yara.dk 🇩🇰",
  },
  {
    url: "https://www.yara.de/",
    countryCode: "DE",
    name: [
      "Deutschland",
      "Deutschland",
      "Allemagne",
      "Deutschland",
      "Alemania",
      "Alemania",
      "Germany",
    ],
    nameToDisplay: "yara.de 🇩🇪",
  },
  {
    url: "https://www.yara.ee/",
    countryCode: "EE",
    name: [
      "Eesti",
      "Eesti",
      "Estonie",
      "Estland",
      "Estonia",
      "Estonia",
      "Estonia",
    ],
    nameToDisplay: "yara.ee 🇪🇪",
  },
  {
    url: "https://www.yara.es/",
    countryCode: "ES",
    name: [
      "España",
      "España",
      "Espagne",
      "Spanien",
      "España",
      "España",
      "Spain",
    ],
    nameToDisplay: "yara.es 🇪🇸",
  },
  {
    url: "https://www.yara.fr/",
    countryCode: "FR",
    name: [
      "Francia",
      "Francia",
      "France",
      "Frankreich",
      "Francia",
      "Francia",
      "France",
    ],
    nameToDisplay: "yara.fr 🇫🇷",
  },
  {
    url: "https://www.yara.hr/",
    countryCode: "HR",
    name: [
      "Hrvatska",
      "Hrvatska",
      "Croatie",
      "Kroatien",
      "Croacia",
      "Croacia",
      "Croatia",
    ],
    nameToDisplay: "yara.hr 🇭🇷",
  },
  {
    url: "https://www.yara.ie/",
    countryCode: "IE",
    name: [
      "Ireland",
      "Ireland",
      "Irlande",
      "Irland",
      "Irlanda",
      "Irlanda",
      "Ireland",
    ],
    nameToDisplay: "yara.ie 🇮🇪",
  },
  {
    url: "https://www.yara.it/",
    countryCode: "IT",
    name: [
      "Italia",
      "Italia",
      "Italie",
      "Italien",
      "Italia",
      "Italia",
      "Italy",
    ],
    nameToDisplay: "yara.it 🇮🇹",
  },
  {
    url: "https://www.yara.nl/",
    countryCode: "NL",
    name: [
      "Nederland",
      "Nederland",
      "Pays-Bas",
      "Niederlande",
      "Países Bajos",
      "Países Bajos",
      "Netherlands",
    ],
    nameToDisplay: "yara.nl 🇳🇱",
  },
  {
    url: "https://www.yara.no/",
    countryCode: "NO",
    name: [
      "Norge",
      "Norge",
      "Norvège",
      "Norwegen",
      "Noruega",
      "Noruega",
      "Norway",
    ],
    nameToDisplay: "yara.no 🇳🇴",
  },
  {
    url: "https://www.yara.pl/",
    countryCode: "PL",
    name: [
      "Polska",
      "Polska",
      "Pologne",
      "Polen",
      "Polonia",
      "Polonia",
      "Poland",
    ],
    nameToDisplay: "yara.pl 🇵🇱",
  },
  {
    url: "https://www.yara.pt/",
    countryCode: "PT",
    name: [
      "Portugal",
      "Portugal",
      "Portugal",
      "Portugal",
      "Portugal",
      "Portugal",
      "Portugal",
    ],
    nameToDisplay: "yara.pt 🇵🇹",
  },
  {
    url: "https://www.yara.ro/",
    countryCode: "RO",
    name: [
      "România",
      "România",
      "Roumanie",
      "Rumänien",
      "Rumania",
      "Rumania",
      "Romania",
    ],
    nameToDisplay: "yara.ro 🇷🇴",
  },
  {
    url: "https://www.yara.ru/",
    countryCode: "RU",
    name: [
      "Россия",
      "Россия",
      "Russie",
      "Russland",
      "Rusia",
      "Rusia",
      "Russia",
    ],
    nameToDisplay: "yara.ru 🇷🇺",
  },
  {
    url: "https://www.yara.se/",
    countryCode: "SE",
    name: [
      "Sverige",
      "Sverige",
      "Suède",
      "Schweden",
      "Suecia",
      "Suecia",
      "Sweden",
    ],
    nameToDisplay: "yara.se 🇸🇪",
  },
  {
    url: "https://www.yara.lv/",
    countryCode: "LV",
    name: [
      "Latvija",
      "Latvija",
      "Lettonie",
      "Lettland",
      "Letonia",
      "Letonia",
      "Latvia",
    ],
    nameToDisplay: "yara.lv 🇱🇻",
  },
  {
    url: "https://www.yara.lt/",
    countryCode: "LT",
    name: [
      "Lietuva",
      "Lietuva",
      "Lituanie",
      "Litauen",
      "Lituania",
      "Lituania",
      "Lithuania",
    ],
    nameToDisplay: "yara.lt 🇱🇹",
  },
  {
    url: "https://www.yara.hu/",
    countryCode: "HU",
    name: [
      "Magyarország",
      "Magyarország",
      "Hongrie",
      "Ungarn",
      "Hungría",
      "Hungría",
      "Hungary",
    ],
    nameToDisplay: "yara.hu 🇭🇺",
  },
  {
    url: "https://www.yara.rs/",
    countryCode: "RS",
    name: ["РСД", "РСД", "Serbie", "Serbien", "Serbia", "Serbia", "Serbia"],
    nameToDisplay: "yara.rs 🇷🇸",
  },
  {
    url: "https://www.yara.fi/",
    countryCode: "FI",
    name: [
      "Suomi",
      "Suomi",
      "Finlande",
      "Finnland",
      "Finlandia",
      "Finlandia",
      "Finland",
    ],
    nameToDisplay: "yara.fi 🇫🇮",
  },
  {
    url: "https://www.yara.co.uk/",
    countryCode: "UK",
    name: [
      "United Kingdom",
      "United Kingdom",
      "Royaume-Uni",
      "Vereinigtes Königreich",
      "Reino Unido",
      "Reino Unido",
      "United Kingdom",
    ],
    nameToDisplay: "yara.co.uk 🇬🇧",
  },
  {
    url: "https://www.yara.gr/",
    countryCode: "GR",
    name: [
      "Ελλάδα",
      "Ελλάδα",
      "Grèce",
      "Griechenland",
      "Grecia",
      "Grecia",
      "Greece",
    ],
    nameToDisplay: "yara.gr 🇬🇷",
  },
  {
    url: "https://www.yara.bg/",
    countryCode: "BG",
    name: [
      "България",
      "България",
      "Bulgarie",
      "Bulgarien",
      "Bulgaria",
      "Bulgaria",
      "Bulgaria",
    ],
    nameToDisplay: "yara.bg 🇧🇬",
  },
  {
    url: "https://www.yara.ua/",
    countryCode: "UA",
    name: [
      "Україна",
      "Україна",
      "Ukraine",
      "Ukraine",
      "Ucrania",
      "Ucrania",
      "Ukraine",
    ],
    nameToDisplay: "yara.ua 🇺🇦",
  },
  {
    url: "https://www.yara.com.ar/",
    countryCode: "AR",
    name: [
      "Argentina",
      "Argentina",
      "Argentine",
      "Argentinien",
      "Argentina",
      "Argentina",
      "Argentina",
    ],
    nameToDisplay: "yara.com.ar 🇦🇷",
  },
  {
    url: "https://www.yara.cl/",
    countryCode: "CL",
    name: ["Chile", "Chile", "Chili", "Chile", "Chile", "Chile", "Chile"],
    nameToDisplay: "yara.cl 🇨🇱",
  },
  {
    url: "https://www.yara.co.nz/",
    countryCode: "NZ",
    name: [
      "New Zealand",
      "New Zealand",
      "Nouvelle-Zélande",
      "Neuseeland",
      "Nueva Zelanda",
      "Nueva Zelanda",
      "New Zealand",
    ],
    nameToDisplay: "yara.co.nz 🇳🇿",
  },
  {
    url: "https://www.yarabrasil.com.br/",
    countryCode: "BR",
    name: [
      "Brasil",
      "Brasil",
      "Brésil",
      "Brasilien",
      "Brasil",
      "Brasil",
      "Brazil",
    ],
    nameToDisplay: "yarabrasil.com.br 🇧🇷",
  },
  {
    url: "https://www.yara.co.za/",
    countryCode: "ZA",
    name: [
      "South Africa",
      "South Africa",
      "Afrique du Sud",
      "Südafrika",
      "Sudáfrica",
      "Sudáfrica",
      "South Africa",
    ],
    nameToDisplay: "yara.co.za 🇿🇦",
  },
  {
    url: "https://www.yara.co.th/",
    countryCode: "TH",
    name: [
      "ประเทศไทย",
      "ประเทศไทย",
      "Thaïlande",
      "Thailand",
      "Tailandia",
      "Tailandia",
      "Thailand",
    ],
    nameToDisplay: "yara.co.th 🇹🇭",
  },
  {
    url: "https://www.yara.id/",
    countryCode: "ID",
    name: [
      "Indonesia",
      "Indonesia",
      "Indonésie",
      "Indonesien",
      "Indonesia",
      "Indonesia",
      "Indonesia",
    ],
    nameToDisplay: "yara.id 🇮🇩",
  },
  {
    url: "https://www.yara.bo/",
    countryCode: "BO",
    name: [
      "Bolivia",
      "Bolivia",
      "Bolivie",
      "Bolivien",
      "Bolivia",
      "Bolivia",
      "Bolivia",
    ],
    nameToDisplay: "yara.bo 🇧🇴",
  },
  {
    url: "https://www.yaracanada.ca/",
    countryCode: "CA",
    name: [
      "Canada",
      "Canada",
      "Canada",
      "Kanada",
      "Canadá",
      "Canadá",
      "Canada",
    ],
    nameToDisplay: "yaracanada.ca 🇨🇦🇬🇧",
  },
  {
    url: "https://www.yaracanada.ca/fr-ca/",
    countryCode: "CA",
    name: [
      "Canada",
      "Canada",
      "Canada",
      "Kanada",
      "Canadá",
      "Canadá",
      "Canada",
    ],
    nameToDisplay: "yaracanada.ca 🇨🇦🇫🇷",
  },
  {
    url: "https://www.yara.com.co/",
    countryCode: "CO",
    name: [
      "Colombia",
      "Colombia",
      "Colombie",
      "Kolumbien",
      "Colombia",
      "Colombia",
      "Colombia",
    ],
    nameToDisplay: "yara.com.co 🇨🇴",
  },
  {
    url: "https://www.yara.com.mx/",
    countryCode: "MX",
    name: [
      "México",
      "México",
      "Mexique",
      "Mexiko",
      "México",
      "México",
      "Mexico",
    ],
    nameToDisplay: "yara.com.mx 🇲🇽",
  },
  {
    url: "https://www.yara.cr/",
    countryCode: "CR",
    name: [
      "Costa Rica",
      "Costa Rica",
      "Costa Rica",
      "Costa Rica",
      "Costa Rica",
      "Costa Rica",
      "Costa Rica",
    ],
    nameToDisplay: "yara.cr 🇨🇷",
  },
  {
    url: "https://www.yara.com.ec/",
    countryCode: "EC",
    name: [
      "Ecuador",
      "Ecuador",
      "Équateur",
      "Ecuador",
      "Ecuador",
      "Ecuador",
      "Ecuador",
    ],
    nameToDisplay: "yara.com.ec 🇪🇨",
  },
  {
    url: "https://www.yara.com.gt/",
    countryCode: "GT",
    name: [
      "Guatemala",
      "Guatemala",
      "Guatemala",
      "Guatemala",
      "Guatemala",
      "Guatemala",
      "Guatemala",
    ],
    nameToDisplay: "yara.com.gt 🇬🇹",
  },
  {
    url: "https://www.yara.com.pa/",
    countryCode: "PA",
    name: [
      "Panamá",
      "Panamá",
      "Panama",
      "Panama",
      "Panamá",
      "Panamá",
      "Panama",
    ],
    nameToDisplay: "yara.com.pa 🇵🇦",
  },
  {
    url: "https://www.yara.com.pe/",
    countryCode: "PE",
    name: ["Perú", "Perú", "Pérou", "Peru", "Perú", "Perú", "Peru"],
    nameToDisplay: "yara.com.pe 🇵🇪",
  },
  {
    url: "https://www.yara.us/",
    countryCode: "US",
    name: [
      "United States",
      "United States",
      "États-Unis",
      "Vereinigte Staaten",
      "Estados Unidos",
      "Estados Unidos",
      "United States",
    ],
    nameToDisplay: "yara.us 🇺🇸",
  },
  {
    url: "https://www.yara.com.au/",
    countryCode: "AU",
    name: [
      "Australia",
      "Australia",
      "Australie",
      "Australien",
      "Australia",
      "Australia",
      "Australia",
    ],
    nameToDisplay: "yara.com.au 🇦🇺",
  },
  {
    url: "https://www.yara.in/",
    countryCode: "IN",
    name: ["India", "India", "Inde", "Indien", "India", "India", "India"],
    nameToDisplay: "yara.in 🇮🇳",
  },
  {
    url: "https://www.yara.com.vn/",
    countryCode: "VN",
    name: [
      "Vietnam",
      "Vietnam",
      "Viêt Nam",
      "Vietnam",
      "Vietnam",
      "Vietnam",
      "Vietnam",
    ],
    nameToDisplay: "yara.com.vn 🇻🇳",
  },
  {
    url: "https://www.yara.my/",
    countryCode: "MY",
    name: [
      "Malaysia",
      "Malaysia",
      "Malaisie",
      "Malaysia",
      "Malasia",
      "Malasia",
      "Malaysia",
    ],
    nameToDisplay: "yara.my 🇲🇾",
  },
  {
    url: "https://www.yara.com.ph/",
    countryCode: "PH",
    name: [
      "Philippines",
      "Philippines",
      "Philippines",
      "Philippinen",
      "Filipinas",
      "Filipinas",
      "Philippines",
    ],
    nameToDisplay: "yara.com.ph 🇵🇭",
  },
  {
    url: "http://www.yara.com.mm/",
    countryCode: "MM",
    name: [
      "Myanmar",
      "Myanmar",
      "Myanmar",
      "Myanmar",
      "Myanmar",
      "Myanmar",
      "Myanmar",
    ],
    nameToDisplay: "yara.com.mm 🇲🇲",
  },
  {
    url: "https://www.yara.kr/",
    countryCode: "KR",
    name: [
      "Korea",
      "Korea",
      "Corée du Sud",
      "Südkorea",
      "Corea del Sur",
      "Corea del Sur",
      "Korea",
    ],
    nameToDisplay: "yara.kr 🇰🇷",
  },
  {
    url: "https://www.yara.com.cn/",
    countryCode: "CN",
    name: ["China", "China", "Chine", "China", "China", "China", "China"],
    nameToDisplay: "yara.com.cn 🇨🇳",
  },
  {
    url: "https://www.yara.cm/",
    countryCode: "CM",
    name: [
      "Cameroon",
      "Cameroon",
      "Cameroun",
      "Kamerun",
      "Camerún",
      "Camerún",
      "Cameroon",
    ],
    nameToDisplay: "yara.cm 🇨🇲🇫🇷",
  },
  {
    url: "https://www.yara.cm/en-cm/",
    countryCode: "CM",
    name: [
      "Cameroon",
      "Cameroon",
      "Cameroun",
      "Kamerun",
      "Camerún",
      "Camerún",
      "Cameroon",
    ],
    nameToDisplay: "yara.cm 🇨🇲🇬🇧",
  },
  {
    url: "https://www.yara.ci/",
    countryCode: "CI",
    name: [
      "Côte d'Ivoire",
      "Côte d'Ivoire",
      "Côte d'Ivoire",
      "Elfenbeinküste",
      "Costa de Marfil",
      "Costa de Marfil",
      "Côte d'Ivoire",
    ],
    nameToDisplay: "yara.ci 🇨🇮",
  },
  {
    url: "https://www.yara.com.gh/",
    countryCode: "GH",
    name: ["Ghana", "Ghana", "Ghana", "Ghana", "Ghana", "Ghana", "Ghana"],
    nameToDisplay: "yara.com.gh 🇬🇭",
  },
  {
    url: "https://www.yara.com.ke/",
    countryCode: "KE",
    name: ["Kenya", "Kenya", "Kenya", "Kenia", "Kenia", "Kenia", "Kenya"],
    nameToDisplay: "yara.com.ke 🇰🇪",
  },
  {
    url: "https://www.yara.ma/",
    countryCode: "MA",
    name: [
      "Morocco",
      "Morocco",
      "Maroc",
      "Marokko",
      "Marruecos",
      "Marruecos",
      "Morocco",
    ],
    nameToDisplay: "yara.ma 🇲🇦",
  },
  {
    url: "https://www.yara.co.tz/",
    countryCode: "TZ",
    name: [
      "Tanzania",
      "Tanzania",
      "Tanzanie",
      "Tansania",
      "Tanzania",
      "Tanzania",
      "Tanzania",
    ],
    nameToDisplay: "yara.co.tz 🇹🇿",
  },
  {
    url: "https://www.yara.co.zm/",
    countryCode: "ZM",
    name: [
      "Zambia",
      "Zambia",
      "Zambie",
      "Sambia",
      "Zambia",
      "Zambia",
      "Zambia",
    ],
    nameToDisplay: "yara.co.zm 🇿🇲",
  },
  {
    url: "https://www.yara.com/",
    countryCode: "",
    name: ["Yara", "com", ".com", "international", "yara.com"],
    nameToDisplay: "yara.com 🌍",
  },
];

export const filterCountries = (
  countryFilterText: string,
  auditsToFilter: fetchedAndSavedAudit[]
) => {
  const filteredCountries = auditsToFilter.filter((audit) => {
    const auditDomain = new URL(audit.url).hostname;
    const correspondingCountryInfo = countryNamesURLAndCountryCode.find(
      (country) => new URL(country.url).hostname === auditDomain
    );
    const isMatchingTheCountry =
      correspondingCountryInfo?.name
        ?.map((name) => name.toLowerCase())
        ?.some((name) => name.includes(countryFilterText)) ||
      correspondingCountryInfo?.countryCode.toLowerCase() === countryFilterText;
    return isMatchingTheCountry;
  });
  return filteredCountries;
};

export const isAuditFilteredByText = (
  countryFilterText: string,
  audit: fetchedAndSavedAudit
) => {
  const auditDomain = new URL(audit.url).hostname;
  const correspondingCountryInfo = countryNamesURLAndCountryCode.find(
    (country) => new URL(country.url).hostname === auditDomain
  );
  const isMatchingTheCountry =
    correspondingCountryInfo?.name
      ?.map((name) => name.toLowerCase())
      ?.some((name) => name.includes(countryFilterText)) ||
    correspondingCountryInfo?.countryCode.toLowerCase() === countryFilterText;
  return isMatchingTheCountry;
};
